name: thegreenredoubt
favicon: null
layout_spectrum: 0.5773599620442837
typography_spectrum: 0.014173392206430435
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#916c35'
    - '#d89551'
    - '#512e04'
    - '#020304'
  brandStrength: 0.9095240300521255
  lightness: 0.5785027593374252
  saturation: 0.02349529298953712
  rhythmicContrast: 0.2712143580429256
purpose: []
