typography_spectrum: 0
color:
  brandColors:
    - '#ffffff'
    - '#916c35'
    - '#d89551'
    - '#512e04'
    - '#020304'
  brandStrength: 0.9095240300521255
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: thegreenredoubt
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Trailer
    id: 461408d4-eb16-43ad-93c9-aa6d7e8160e1
    type: content
  - name: Put A Coin On The Brim Of My Hat
    id: ca7d0e26-bd6d-47c6-b1bc-8eae14819e29
    type: content
  - name: The Butterfly Collector
    id: 998f92f3-d3e8-4b3f-bd9a-d3b3b44ad268
    type: content
  - name: Map of The Green Redoubt
    id: 449609a2-3661-4515-a686-c41d2c119a71
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b461f1e3-f90a-40d4-82f8-2f8647177033.jpg
title: 'servus princeps, dictator papyrus - we are but princes, bureaucracy is king'
purpose: []
