typography_spectrum: 0.23205131059512496
content_rating:
  adult: true
color:
  brandColors:
    - '#ffffff'
    - '#916c35'
    - '#d89551'
    - '#512e04'
    - '#020304'
  brandStrength: 0.9095240300521255
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7917504315264523
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Nick Larter
  url: 'http://twitter.com/thremnir'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/981e7694-999d-4f24-8cbc-d1dc6aee0786.jpg
name: The Green Redoubt
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: What Am I Doing Here?
    id: 3a6fc9f7-a69f-465e-b5bd-f39d19a13c4e
    type: content
  - name: The Butterfly Collector
    id: 998f92f3-d3e8-4b3f-bd9a-d3b3b44ad268
    type: content
  - name: Put A Coin On The Brim Of My Hat
    id: ca7d0e26-bd6d-47c6-b1bc-8eae14819e29
    type: content
  - name: 'The Green Redoubt: Trailer'
    id: 461408d4-eb16-43ad-93c9-aa6d7e8160e1
    type: content
  - name: Like A Garden No-one Is Allowed To See
    url: 'http://thremnir.wordpress.com/'
    type: external
  - name: My Twitter Feed
    url: 'http://twitter.com/thremnir'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b461f1e3-f90a-40d4-82f8-2f8647177033.jpg
title: 'Servus Princeps, Dictator Papyrus'
description: 'We are but Princes, Bureaucracy is King'
purpose: []
