name: thegreenredoubt
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: 'servus princeps, dictator papyrus - we are but princes, bureaucracy is king'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#916c35'
    - '#d89551'
    - '#512e04'
    - '#020304'
  brandStrength: 0.9095240300521255
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
